Repository git-baboo/easy-review, pull requests merged in 2022-01, with the labels that each got.

#182 差分がファイル削除の場合、その旨を表示させる
  src/components/review/DiffFile.tsx
Labels: feature, ui

#189 DiffFile.tsx の type の型定義と分岐条件の修正
  src/components/review/DiffFile.tsx
Labels: bug, refactor

#192 Detail ページと Review ページのプルリク情報部分を共通化する
  src/components/PullRequestHeading.tsx
  src/components/detail/Reviewee.tsx
  src/components/review/PullRequestHeading.tsx
  src/pages/[owner]/[repo]/[pullNumber]/index.tsx
  src/pages/[owner]/[repo]/[pullNumber]/review.tsx
Labels: refactor

#191 差分表示において、バイナリファイルの場合、その旨を表示する
  src/components/review/DiffFile.tsx
  src/components/review/DiffFileList.tsx
Labels: feature, ui

#207 不要なプロパティの削除
  src/components/PullRequestHeading.tsx
  src/components/review/DiffFile.tsx
  src/pages/[owner]/[repo]/[pullNumber]/review.tsx
Labels: ui, refactor

#196 PR が1つも表示されない場合にメッセージを表示する
  src/components/top/NoPullsMessage.tsx
  src/pages/index.tsx
Labels: feature
